# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: debug
  logs:
    custom_components.rtl_433_ha_http: debug
